@ApplicatinNameApi_HostAddress = https://localhost:5001

GET {{ApplicatinNameApi_HostAddress}}/
Accept: application/json

Response
{
    "message": "SPAR Api is alive and kicking!"
}

###

GET {{ApplicatinNameApi_HostAddress}}/personal-data
Accept: application/json

###

POST {{ApplicatinNameApi_HostAddress}}/personal-data
Accept: application/json
Content-Type: application/json

{
    "identifieringsinformation": {
      "kundNrLeveransMottagare": 1,
      "kundNrSlutkund": 2,
      "uppdragId": 3,
      "slutAnvandarId": "4",
      "slutAnvandarUtokadBehorighet": [0]
    },
    "personsokningFraga": {
      "items": [
        "123456"
      ],
      "itemsElementName": [
        0
      ]
    }
}