name: spar
services:
  api:
    build:
      context: ./SPAR-Api/
      dockerfile: ../SPAR-Api/Dockerfile
    ports:
      - '5001:443'
    volumes:
      - ./Certificates:/https/:ro
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    user: postgres
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty123!
      POSTGRES_DB: spar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - '8080:8080'
  seq:
    image: datalust/seq:2024.2
    ports:
      - '5341:80'
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_API_CORSALLOWEDORIGINS: 'https://localhost:5001'
